services:
  dia-hex-map:
    container_name: dia-hex-map
    build: .
    ports:
      - "9876:9876"
    environment:
      - PORT=9876
    command: pnpm run start
    restart: unless-stopped
    networks:
      - network

  mariadb:
    container_name: dia-mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dia_hex_map
      MYSQL_USER: dia_hex_map
      MYSQL_PASSWORD: dia_hex_map
    volumes:
      - /home/sjohnson/data/dia/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - network

  adminer:
    container_name: dia-adminer
    image: adminer:latest
    ports:
      - "38848:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dia-mariadb
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    name: my-bridge-network
    external: true
